apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: pokemon
  labels:
    app: pokemon-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-app
  template:
    metadata:
      labels:
        app: pokemon-app
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '8000'
    spec:
      containers:
      - name: pokemon-container
        image: omeritzhaki/pokemon-fetcher:0.0.1
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
