apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: pokemon-app
spec:
  type: ClusterIP
  selector:
    app: pokemon-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
